name: Auto Docker Build toolbox ikuaiapp

on:
  push:
    branches:
      - master
    paths:
      - Dockerfile
      - README.md
      - .github/workflows/Auto-Docker-Build-toolbox-ikuaiapp.yml

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME_IKUAIAPP }}
        password: ${{ secrets.DOCKER_PASSWORD_IKUAIAPP}}

    - name: Build and push multi-platform images
      id: build-and-push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME_IKUAIAPP }}/${{ github.event.repository.name }}:latest
        # ${{ secrets.DOCKER_USERNAME }}/toolbox:${{ github.sha }}
    
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME_IKUAIAPP }}
        password: ${{ secrets.DOCKER_PASSWORD_IKAUIAPP }}
        repository: ${{ secrets.DOCKER_USERNAME_IKUAIAPP }}/toolbox
        short-description: toolbox
        readme-filepath: ./README.md
